config/routes.rb
Rails.application.routes.draw do

  get 'pages/home' => "pages#home"
get 'pages/home_alt' => "pages#home_alt"
  get '/results' => 'pages#results'

  get 'pages/about'

  get 'pages/faq'

  root "pages#home_alt"
  get "/users/edit" => 'users#edit', :as => "edit_user"
  resources :users, :except => [:edit]
  resources :countries, :cities, :tours
  get '/login' => 'session#new', :as => "login"
  post '/login' =>'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"

end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :text
#  top_facts  :text
#  highlights :text
#  image      :text
#  country_id :integer
#

class City < ActiveRecord::Base
  belongs_to :country
  has_and_belongs_to_many :tours
end

app/models/country.rb
# == Schema Information
#
# Table name: countries
#
#  id         :integer          not null, primary key
#  name       :string
#  top_facts  :text
#  highlights :text
#  weather    :text
#  image      :text
#

class Country < ActiveRecord::Base
  has_many :cities
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :cities
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  title             :string
#  first_name        :string
#  last_name         :string
#  email             :string
#  dob               :date
#  gender            :string
#  contact_number    :integer
#  address_line_1    :string
#  address_line_2    :string
#  suburb            :string
#  state             :string
#  postcode          :string
#  diet              :text
#  medical_condition :text
#  admin             :boolean          default(FALSE)
#  password_digest   :text
#

class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :tours
  validates :contact_number, :numericality => {:only_integer => true}
  validates_format_of :title, :first_name, :last_name, :suburb, :state, :with => /\A[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private

  def fetch_user
    @current_user = User.find_by(id: session[:user_id]) if
    session[:user_id]

    session[:user_id] = nil unless @current_user.present?
  end
end

app/controllers/cities_controller.rb
require 'open_weather'

class CitiesController < ApplicationController




  def index
    @cities = City.all
  end

  def show
    @city = City.find params[:id]
    options = { units: "metric", APPID: Rails.application.secrets.open_weather_password }
    @weather = OpenWeather::Current.city("#{@city.name}, #{@country_code}", options)
  end

  def new
    @city = City.new
  end

def create
  city = City.create (city_params)

  redirect_to "/cities/#{city.id}"
end

  def edit
    @city = City.find params[:id]
  end

def update
  city = City.find params[:id]
  city.update(city_params)
  redirect_to city

  # redirect_to "/cities/#{city.id}"

end

def destroy
city = City.find params[:id]
city.destroy
redirect_to "/cities"
end

private

def city_params
  params.require(:city).permit(:name, :top_facts, :highlights, :image, :country_id)
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end

  def show
    @country = Country.find params[:id]
end

  def new
    @country = Country.new
  end

def create
  country = Country.create (country_params)
  redirect_to "/countries/#{country.id}"
end

  def edit
    @country = Country.find params[:id]
  end

def update
  country = Country.find params[:id]
  country.update(country_params)
  redirect_to country

end

def destroy
country = Country.find params[:id]
country.destroy
redirect_to "/countries"
end

private

def country_params
  params.require(:country).permit(:name, :top_facts, :highlights, :weather, :image)
end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end

  def test
  if params[:country_id].present?
    form.select[:city_id, disabled =>['true']]
  end
end

  def results
    if params[:country_id].present?
    @country = params[:country_id]
      redirect_to country_path(@country)
    elsif params[:city_id].present?
      @city = params[:city_id]
      redirect_to city_path(@city)
    elsif params[:tour_id].present?
      @tour = params[:tour_id]
      redirect_to tour_path(@tour)
    else
      redirect_to pages_home_path
    end
    # @city = params[:city_id]
    # @tour = params[:tour_id]

    # This is where get requests from our pages _form will get sent. It will need to handle the logic of returning records based on the queries in params.
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      flash[:success] = 'User successfully logged in'
      session[:user_id] = user.id
      redirect_to users_path
    else
      flash[:error] = 'Your password or email is incorrect'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'you have successfully logged out'
    redirect_to users_path
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @tours = Tour.all
  end

  def show
    @tour = Tour.find params[:id]
  end

  def new
    @tour = Tour.new
  end

  def create
    tour = Tour.create tour_params
    redirect_to "/tours/#{tour.id}"
  end

  def edit
    @tour = Tour.find params[:id]
  end

  def update
    tour = Tour.find params[:id]
    tour.update(tour_params)
    redirect_to tour
    end

  def destroy
    tour = Tour.find params[:id]
    tour.destroy
    redirect_to '/tours'
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :theme, :duration, :top_facts, :highlights, :price, :image, :start_date, :end_date, {city_ids:[]})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorise, only: [:index, :edit]

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = 'User was successfully created'
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash[:error] = 'Please try again'
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    user = @current_user
    user.update user_params

    redirect_to user_path(user)
  end

  def destroy
    user = @current_user
    user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :title, :first_name, :last_name, :dob, :contact_number, :address_line_1, :address_line_2, :suburb, :state, :postcode, :diet, :medical_condition)
  end

  def authorise
    flash[:error] = 'Please login to view' unless @current_user.present?
    redirect_to login_path unless @current_user.present?
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
    <%= form_for @city do |f| %>
        <p>
            <br>
            <br>
            <%= f.label :name %>
            <%= f.text_field :name, :required => true %>
        </p>
        <p>
            <%= f.label :top_facts %>
            <%= f.text_area :top_facts, rows: 5, :required => true %>
        </p>
        <p>
            <%= f.label :highlights %>
            <%= f.text_area :highlights, rows: 5, :required => true %>
        </p>
        <p>
            <%= f.label :image %>
            <%= f.text_field :image, :required => true %>
        </p>
        <p>
             <%= f.label :country %>
            <%= f.collection_select(:country_id, Country.all, :id, :name)%>
        </p>
        <%= f.submit "Submit", :class => "submit_format" %>
    <% end %>

app/views/cities/edit.html.erb
<h2>Edit
    <!-- <p>Find me in app/views/cities/edit.html.erb</p> -->

    <%= @city.name %></h2>

<%= render :partial => 'form' %>

app/views/cities/index.html.erb
<h1>CITY BREAKS</h1>
<!-- <p>Find me in app/views/cities/index.html.erb</p> -->

<ul>
    <div class="container--grid">

        <% @cities.each do |a| %>
        <li class="list--grid-medium">
            <div class="box-medium">

                <h5>
                    <%= link_to(a.name.upcase, "/cities/#{a.id}") %>
                </h5>

                    <p></p>
                    <div class="image-medium">
                        <%= image_tag(a.image) %>
                    </div>
            </div>
        </li>

        <% end %>
    </div>
</ul>

app/views/cities/new.html.erb
<h1>Cities</h1>
<!-- <p>Find me in app/views/cities/new.html.erb</p> -->


<%= render :partial => 'form' %>

app/views/cities/show.html.erb
<h1></h1>
<ul>
    <div class="container--grid">
    <li class="container-medium">

        <h2 class="header--city-left"><%= @city.name.upcase %></h2>
        <br>
        <div class="header--weather-left">
            <% if @city.country.name =="Germany" %>
                <% @country_code = "DE" %>
            <% else %>
                <%@country_code = "FR"  %>
            <% end %>
            <%= p "Current Temp: #{@weather["main"]["temp"].to_i}" %>
            <%= p "Min: #{@weather["main"]["temp_min"].to_i}" %>
            <%= p "Max: #{@weather["main"]["temp_max"].to_i} (c)" %>
            <%= p "Weather: #{@weather["weather"].first["main"]}"%>
            <%= image_tag "http://openweathermap.org/img/w/#{ @weather["weather"].first["icon"] }.png", :size => "20x20", :class =>"icon" %>
            <br>
        </div>

        <div class="city-country-header">
            <% if @city.country %>
            <%= link_to(@city.country.name, @city.country) %>
            <p></p>
            <p></p>
            <%end %>
        </div>

        <p></p>
        <p></p>
        <div class="container--innerbox-medium">
            <%= image_tag (@city.image) %>
        </div>
    </li>
    <br class="fix">

    <li class="container-medium bottom">
        <div class="container--innerbox-medium">
            <%="Top Facts are: #{@city.top_facts}" %>
            <p></p>

            <%="Main highlights are: #{@city.highlights}" %>
            <p></p>
            <p></p>
            <p>Current Tours below:</p>
            <% @city.tours.each do |tour| %>
            <%= link_to tour.name, tour_path(tour.id) %>
            <br>
            <%end  %>
        </div>
    </li>
    </div>
</ul>
<hr>

<h3 class="header--city-center">
    Explore <%=@city.name%> Attractions
</h3>
<ul>
    <div class="container--grid">
    <li class="container-medium">
        <div class="container--innerbox-medium">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut tenetur libero consequuntur veritatis quas ex rerum distinctio ad, nam officiis magni, nobis laboriosam assumenda nulla voluptatibus molestiae earum ea enim?
            </p>

        </div>
    </li>
    <li class="container-medium">
        <div class="container--innerbox-medium">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum sint odit recusandae. Corporis sunt rem, hic deserunt, laboriosam repellendus ea soluta exercitationem blanditiis modi similique explicabo iure eius nobis nulla!
            </p>
        </div>
    </li>
    </div>
</ul>

 <div class="controls controls-center">
            <% if @current_user == nil %>
            <% %>
            <%elsif @current_user.admin.to_s == "true"  %>
            <%= link_to "Edit city", edit_city_path(@city.id) %>
            <%= link_to "Delete city", @city, :method => :delete, :data => { :confirm => "Please confirm?"} %>
            <%end %>

 </div>
 <br>

app/views/countries/_form.html.erb
<%= form_for @country do |f| %>
  <p>
    <br>
    <br>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
  </p>
  <p>
    <%= f.label :top_facts %>
    <%= f.text_area :top_facts, rows: 5, :required => true %>
  </p>
  <p>
    <%= f.label :highlights %>
    <%= f.text_area :highlights, rows: 5, :required => true %>
  </p>
  <p>
    <%= f.label :weather %>
    <%= f.text_field :weather, :required => true %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.text_field :image, :required => true %>
  </p>

  <%= f.submit "Submit", :class => "submit_format" %>
<% end %>

app/views/countries/edit.html.erb
<h1>Edit Country</h1>
<p></p>

<%= render :partial => 'form' %>

app/views/countries/index.html.erb
<h1>DESTINATIONS</h1>
<!-- <p>Find me in app/views/countries/index.html.erb</p> -->

<ul>
    <div class="container--grid">
        <% @countries.each do |a| %>
        <li class="list--grid-small">
            <div class="box-small">
                <div class="image-small <%=a.name%>">
                     <%= image_tag(a.image) %>
                </div>

                <div class="textbox-small <%=a.name%>">
                    <h3>
                     <%= link_to(a.name.upcase, "/countries/#{a.id}") %>
                    </h3>
                </div>
            </div>
        </li>
        <% end %>

    </div>
</ul>

<ul>
    <div class="container--grid">
        <li class="list--grid-small">
            <p class="text--grid">Something witty and funny to say here.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur facere obcaecati, fugit tempora, incidunt voluptatem, earum, sapiente qui ratione dolor cumque necessitatibus nisi vel accusantium aut numquam voluptates eligendi animi.</p>
        </li>
        <li class="list--grid-small">
            <p class="text--grid">Something even more funny to say.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur facere obcaecati, fugit tempora, incidunt voluptatem, earum, sapiente qui ratione dolor cumque necessitatibus nisi vel accusantium aut numquam voluptates eligendi animi.</p>
        </li>
        <li class="list--grid-small">
            <p class="text--grid">Dry sarcasm best with a bitter twist.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequuntur facere obcaecati, fugit tempora, incidunt voluptatem, earum, sapiente qui ratione dolor cumque necessitatibus nisi vel accusantium aut numquam voluptates eligendi animi.</p>
        </li>
    </div>
</ul>

<hr>

app/views/countries/new.html.erb
<h1>Add Country</h1>
<p></p>

<%= render :partial => 'form' %>

app/views/countries/show.html.erb
<ul>
    <h1><%= "Cities in #{@country.name}" %></h1>
    <div class="container--grid">



    <li class="container-medium">
        <div class="container--innerbox-medium">
            <%= image_tag(@country.image) %>
        </div>

    </li>
    <br class="fix">

    <li class="container-medium">
        <div class="container--innerbox-medium">
            <%="Top Facts are: #{@country.top_facts}" %>
            <p></p>
            <%="Main highlights are: #{@country.highlights}" %>
            <p></p>
            <%="Climate: #{@country.weather}" %>
          <p>Current Cities below:</p>
                      <% @country.cities.each do |w|  %>
                      <%= link_to(w.name, "/cities/#{w.id}") %>
                      <br>
                      <%end  %>

        </div>
    </li>
    </div>
</ul>

<hr>

<h3 class="header--city-center">
    Discover <%=@country.name%>
</h3>

<ul>
    <div class="container--grid">
    <li class="container-medium">
        <div class="container--innerbox-medium">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos necessitatibus perferendis officia consequuntur optio reiciendis excepturi ducimus vel repellat corporis, alias distinctio tempore corrupti dolor aliquam rem totam aut perspiciatis.
        </div>
    </li>
    <li class="container-medium">
        <div class="container--innerbox-medium">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo praesentium, dignissimos tempora aperiam illum aspernatur nam debitis dicta impedit assumenda! Pariatur adipisci, asperiores fugiat dolor fugit commodi assumenda? Soluta, reiciendis?
        </div>
    </li>
    </div>
</ul>

<div class="autoplay">

    <div>
        <%= image_tag("panoramic-alhambra.jpg", :class => "autoplay") %>
    </div>
    <div>
        <%= image_tag("panoramic-mountains.jpg", :class => "autoplay") %>
    </div>

    <div>
        <%= image_tag("forest.jpg", :class => "autoplay") %>
    </div>
    <div>
        <%= image_tag("prague_panoramic.jpg", :class => "autoplay") %>
    </div>
    <div>
        <%= image_tag("beach.jpg", :class => "autoplay") %>
    </div>

    </div>

<br>
<br>
<div class="controls controls-center">
    <% if @current_user == nil %>
    <% %>
    <%elsif @current_user.admin.to_s == "true"  %>
    <%= link_to "Edit Country", edit_country_path(@country.id) %>
    <%= link_to "Delete Country", @country, :method => :delete, :data => { :confirm => "Please confirm?"} %>
    <%end %>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//fonts.googleapis.com/css?family=Lato|Montserrat|Acme" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
</head>
<body class="<%= params[:controller] %> <%= params[:action] %>">

  <% if session[:important] %>
  <h1><%= session[:important] %></h1>
  <%end %>

  <% if flash[:success] %>
  <h1>
    <%= flash[:success] %>
  </h1>
  <% end %>

  <% if flash[:error] %>
  <h1>
    <%= flash[:error] %>
  </h1>
  <% end %>


  <nav>
    <ul class="navbar" id="myNavBar">
        <div class="center--list">
            <li>
                <a id="icon-responsive" href="javascript:void(0);" onclick="navBarFunction()">&#9776;</a>
            </li>
            <li id="span--container">
                <span class="nav-logo">Remarkable Voyages</span>
            </li>
            <li>
                <%= link_to("Home", pages_home_alt_path) %>
            </li>
            <li>
                <%= link_to("Countries", "/countries")%>
            </li>
            <li>
                <%= link_to("Cities", "/cities") %>
            </li>
            <li>
                <%= link_to("Tours", "/tours") %>
            </li>
        <% unless @current_user.present? %>
            <li>
                <%= link_to("Login", login_path()) %>
            </li>
            <li>
                <%= link_to("Sign Up", new_user_path()) %>
            </li>
        <%else %>
            <li>
                <%= link_to("Edit your profile", edit_user_path(@current_user.id)) %>
            </li>
            <li>
                <%= link_to("Log out #{@current_user.first_name} #{@current_user.last_name}", logout_path, :method => :delete) %>
            </li>
        <% end %>
        </div>
    </ul>
  </nav>


<div class="container">

  <div class="push-footer">
    <br>
  </div>

  <%= yield %>



  </div>

<footer>
    <div class="footer-style">
    Remarkable Voyages is a simple travel website created as an educational project for General Assembly's Web Development Immersive Course by Stephen Gibbs
    </div>
  </footer>

</body>
</html>

app/views/pages/_form.html.erb
<%=form_tag('/results', :method => 'get', :class => "search") do %>

<p></p>

<%= label_tag(:country) %>
<%= collection_select(nil, :country_id, Country.all, :id, :name, :include_blank => :true) %>

<%= label_tag(:city) %>
<%= collection_select(nil, :city_id, City.all, :id, :name, :include_blank => :true) %>

<%= label_tag(:tour) %>
<%= collection_select(nil, :tour_id, Tour.all, :id, :name, :include_blank => :true) %>

<%= submit_tag "Submit Search", :class => "submit_format1" %>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<!-- <p>Find me in app/views/pages/home.html.erb</p> -->
<h1 class="header">Remarkable Voyages</h1>
<p class="home2">
    <%= render :partial => "form" %>
</p>

app/views/pages/home_alt.html.erb
<h1 class="header">Remarkable Voyages</h1>
<%= render :partial => "form" %>

<div class="parallax-view">
<p class="parallax-text"></p>
</div>


<div class="parallax-bottom-space">
<h1 class="parallax-bottom-space">Latest News from Remarkable Voyages
  <p class="parallax-bottom-space">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda similique dolor quos nulla cumque vitae deleniti, quis, incidunt officiis ea quo maiores qui eaque aliquid porro quas voluptatum nemo velit.  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tempora nobis velit, fugiat explicabo officiis quibusdam in repudiandae rem adipisci commodi praesentium sit odit iste corporis eligendi, ducimus sint, impedit pariatur.
  </p>
</h1>
</div>

app/views/pages/results.html.erb
<%= p @country %>
<%= p @country_name %>
<%#= link_to "../countries/#{@country}"%>
<%#=link_to "France", country_path(@country)%>
<!--<%=link_to Country.find(@country).name, country_path(@country)%> -->

<%#= redirect_to country_path(@country)%>


<%= p @tour %>
<%= p @city %>

app/views/session/new.html.erb
<h1>Login</h1>
<!-- <p>Find me in app/views/session/new.html.erb</p> -->

<%= form_tag login_path, :class => "login_form" do %>

    <br>
    <br>
    <%= label_tag :email %>
    <%= email_field_tag :email, "", :required => true %>
    <br>
    <%= label_tag :password %>
    <%= password_field_tag :password, "", :required => true %>


<%= submit_tag "Login", :class => "submit_format" %>
<% end %>

app/views/tours/_form.html.erb
<%= form_for @tour do |f| %>
    <p>
        <br>
        <br>
        <%= f.label :name %>
        <%= f.text_field :name, :required => true %>
    </p>
    <p>
        <%= f.label :theme %>
        <%= f.text_field :theme, :required => true %>
    </p>
    <p>
        <%= f.label :duration %>
        <%= f.text_field :duration, :required => true %>
    </p>
    <p>
        <%= f.label :top_facts %>
        <%= f.text_area :top_facts, rows: 5, :required => true %>
    </p>
    <p>
        <%= f.label :highlights %>
        <%= f.text_area :highlights, rows: 5, :required => true %>
    </p>
    <p>
        <%= f.label :price %>
        <%= f.text_field :price, :required => true %>
    </p>
    <p>
        <%= f.label :image %>
        <%= f.text_field :image, :required => true %>
    </p>
    <p>
        <%= f.label :start_date %>
        <%= f.text_field :start_date, :required => true %>
    </p>
    <p>
        <%= f.label :end_date %>
        <%= f.text_field :end_date, :required => true %>
    </p>

    <p>
        <%= f.collection_check_boxes(:city_ids, City.all, :id, :name) %>
    </p>
    <%= f.submit "Submit", :class => "submit_format" %>
<% end %>

app/views/tours/edit.html.erb
<h1>Edit</h1>
<!-- <p>Find me in app/views/tours/edit.html.erb</p> -->

<%= render :partial => 'form' %>

app/views/tours/index.html.erb
<h1>TOURS</h1>

<ul>
    <div class="container--grid">
        <% @tours.each do |a| %>
        <li class="list--grid-small">
            <div class="box-small">
                <div class="image-small">
                    <%= image_tag(a.image) %>
                </div>

            <div class="textbox-small">
               <h4>
               <%= link_to(a.name.upcase, "/tours/#{a.id}") %>
               </h4>
            </div>
        </div>
        </li>
        <% end %>

    </div>
</ul>

app/views/tours/new.html.erb
<h1>Add Tour</h1>
<p></p>

<%= render :partial => 'form' %>

app/views/tours/show.html.erb
<h1></h1>

<ul>
    <div class="container--grid">
    <li class="container-medium">

        <h2 class="header--tour-left"><%= "#{@tour.name.upcase}"%></h2>
        <br>
        <div class="container--innerbox-medium">
            <%= image_tag (@tour.image) %>
        </div>
    </li>


<br class="fix">

     <li class="container-medium bottom">
        <div class="container--innerbox-medium">

            <%="Top Facts are: #{@tour.top_facts}" %>
            <p></p>
            <%="Main highlights are: #{@tour.highlights}" %>
            <p></p>
            <div>Cities for the tour are:</div>
            <p></p>

            <% @tour.cities.each do |city| %>
            <%= link_to city.name, city_path(city.id) %>
            <br>
            <%end  %>
        </div>

     </li>
    </div>
</ul>
<hr>
<h3 class="header--city-center">
    Main Tour Attractions
</h3>
<ul>
    <div class="container--grid">
    <li class="container-medium">
        <div class="container--innerbox-medium">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut tenetur libero consequuntur veritatis quas ex rerum distinctio ad, nam officiis magni, nobis laboriosam assumenda nulla voluptatibus molestiae earum ea enim?
            </p>

        </div>
    </li>
    <li class="container-medium">
        <div class="container--innerbox-medium">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum sint odit recusandae. Corporis sunt rem, hic deserunt, laboriosam repellendus ea soluta exercitationem blanditiis modi similique explicabo iure eius nobis nulla!
            </p>
        </div>
    </li>
    </div>
</ul>

<div class="controls controls-center">
    <% if @current_user == nil %>
    <% %>
    <%elsif @current_user.admin.to_s == "true"  %>
    <%= link_to "Edit tour", edit_tour_path(@tour.id) %>
    <%= link_to "Delete tour", @tour, :method => :delete, :data => { :confirm => "Please confirm?"} %>
    <%end %>
</div>
<br>

app/views/users/show.html.erb
<!-- <p>Find me in app/views/users/show.html.erb</p> -->

<h1><%= "User account for #{@user.first_name} #{@user.last_name}"%></h1>


<% @user.tours.each do |tour| %>
<%= "Tours booked:" %>
<p></p>
<%= link_to(tour.name, tour_path(tour)) %>
<% end %>


<ul>
    <div class="user3">
        <li><%= "Email address: #{@user.email}" %></li>
        <li><% if @user.admin.to_s == "false" %></li>
        <li><%= "Account Privileges: Customer" %></li>
    <% else %>
        <%= "Account Privileges: Administrator" %>
        <%end %>
    </ul>
</div>

<%if @current_user && @current_user.id == @user.id %>
<div class="controls">
    <%= link_to "Edit", edit_user_path(@user.id) %>
    <%= link_to "Delete Account", user_path(@user.id), :method => :delete %>
</div>

<%end %>
<nav>
    <% if @user.admin.to_s == "true"  %>
    <%= link_to "Create a new country", "/countries/new" %>
    <%= link_to "Create a new city", "/cities/new" %>
    <%= link_to "Create a new tour", "/tours/new" %>
    <%=     link_to("All Users", users_path) %>
    <%end %>
</nav>